externalService :
  category :
    url : http://localhost:5977/categories
  lineproduct:
    url: http://localhost:6077/lineproducts

server:
  port: 5877

spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: PRODUCT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  istance:
    hostname: localhost





















