server :
  port : 6077

spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: LINEPRODUCT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  istance:
    hostname: localhost