externalService :
  product:
    url: http://localhost:5877/products
  order:
    url: http://localhost:6077/lineproducts


server :
  port : 6077

spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: LINEPRODUCT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  istance:
    hostname: localhost