externalService :
  order:
    url: http://localhost:6077/lineproducts

server :
  port : 6277

spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  istance:
    hostname: localhost