externalService :
  product:
    url: http://localhost:5877/products

server :
  port : 5977

spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: CATEGORY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  istance:
    hostname: localhost









